### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/XPSpawners#3]
What license are you releasing this under @soerxpso

**Comment by sepiatonal** [comment]
Not sure. What would you recommend?

**Comment by ProgrammerDan** [comment]
If you don't mind people using it for whatever, MIT or BSD 3-clause (what I usually use). 

If you do mind, use a GPL-series license. LGPL isn't horrible iirc, although the most recent versions are kind of "militant foss" in design.
