### ISSUE TITLE
Example Config

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/XPSpawners#4]
Please include an example config under src/main/resources

**Comment by ProgrammerDan** [comment]
In example config be sure to note what units are in play: https://github.com/DevotedMC/XPSpawners/blob/master/src/main/java/com/github/soerxpso/xpspawners/manager/ConfigManager.java#L16

(ticks, milliseconds, seconds, etc).

**Comment by sepiatonal** [comment]
Will add tomorrow.
