### ISSUE TITLE
Delay drop of spawner when silk touched

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/XPSpawners#5]
To be sure there is no bouncing, delay the drop of the spawner by one tick (check HiddenOre's adaptation of Gordon's code)

Here:
https://github.com/DevotedMC/XPSpawners/blob/master/src/main/java/com/github/soerxpso/xpspawners/listeners/BlockListener.java#L29

**Comment by sepiatonal** [comment]
Will add tomorrow.
